### ISSUE TITLE
Client类中关于线程休眠的问题

### ISSUE THREAD

**Issue by gaowenming** [slimina/thrift-zookeeper-rpc#2]
ApplicationContext context = new ClassPathXmlApplicationContext("spring-context-thrift-client.xml");
            EchoSerivce.Iface echoSerivce = (EchoSerivce.Iface) context.getBean("echoSerivce");
            Thread.sleep(1000);
            for (int i = 0; i < 100; i++) {
                Thread.sleep(3000);
                try {
                    System.out.println(echoSerivce.echo("hello----"+i));
                } catch (Exception e) {
                    e.printStackTrace();
                }
                //TThread t = new TThread(echoSerivce);
                //t.start();
            }
            Thread.sleep(3000000);

在测试的时候发现，如果把Thread.sleep(1000);去掉的话，会出现
java.lang.NullPointerException
at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1188)

如果把Thread.sleep(3000000);会出现
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
    at sun.nio.ch.SocketDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:197)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
    at org.apache.thrift.transport.TNonblockingSocket.read(TNonblockingSocket.java:142)
    at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.internalRead(AbstractNonblockingServer.java:539)
    at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.read(AbstractNonblockingServer.java:338)
    at org.apache.thrift.server.AbstractNonblockingServer$AbstractSelectThread.handleRead(AbstractNonblockingServer.java:203)
    at org.apache.thrift.server.TThreadedSelectorServer$SelectorThread.select(TThreadedSelectorServer.java:586)
    at org.apache.thrift.server.TThreadedSelectorServer$SelectorThread.run(TThreadedSelectorServer.java:541)

在实际环境中，肯定不会用休眠的方式吧？

**Comment by slimina** [comment]
这里面代码只是一个demo，还不完善，如果借助tomcat这样的容器就不需要sleep，也可以向dubbo那样使用，主类wait的方式，进入等待。
 synchronized (Main.class) {
            while (running) {
                try {
                    Main.class.wait();
                } catch (Throwable e) {
                }
            }
        }

**Comment by gaowenming** [comment]
我把server已经改成容器启动方式，client采用springTest方式，还是一样会出现上面的问题，请问对client的调用有使用实例吗？

**Comment by slimina** [comment]
恩 问题产生的原因是zk还没有连接上，就去调用服务，所以会出现空指针。之前我是sleep等待了一下。我已经调整，在ThriftServerAddressProviderZookeeper里面添加了CountDownLatch控制。客户端不会出现问题。
关于服务端出现“java.io.IOException: 远程主机强迫关闭了一个现有的连接。”，由于客户端与服务端连接被强制管理导致，springtest方式除非手动closeTServiceClient。由于ThriftServiceClientProxyFactory重写了close方法，在tomcat容器里面spring会自动调用close方法，应该不会出现问题。

请更新最新代码。

**Comment by slimina** [comment]
```
proxyClient = Proxy.newProxyInstance(classLoader, new Class[] { objectClass }, new InvocationHandler() {
        @Override
        public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
            //
            TServiceClient client = pool.borrowObject();
            boolean flag = true;
            try {
                return method.invoke(client, args);
            } catch (Exception e) {
                flag = false;
                throw e;
            } finally {
                                     //手动关闭客户端可服务端链接，不建议，这样不能有效的使用链接
                client.getInputProtocol().getTransport().close();
                client.getOutputProtocol().getTransport().close();
            }
        }
    });
```

**Comment by gaowenming** [comment]
非常感谢，其实thrift和zookeeper集成这一块，apache官方好像没有做相关的工作，dubbo到是把zookeeper注册这一块直接集成进去了，对于使用者来说，方便了很多

**Comment by lq08025107** [comment]
对于“ 远程主机强迫关闭了一个现有的连接”这个问题，其实是客户端没有正常close，直接手动关闭链接的确会导致池中的对象无效。所以springtest中缺少的一点是将context关闭，((ConfigurableApplicationContext)context).close();这样对象池会正常关闭所有链接，像作者说的那样用tomcat管理也许可以吧，没试过。
